#!/bin/bash
source ~/venv/bin/activate
rm -rf pythontex-files-*

FILE="queueing_book"
pdflatex $FILE
pythontex --interpreter python:python3 $FILE
pdflatex $FILE
makeindex $FILE
pdflatex $FILE

FILE="companion"
pdflatex $FILE
pythontex --interpreter python:python3 $FILE
pdflatex $FILE
makeindex $FILE
pdflatex $FILE



